import {KoHo } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar"
import { OpenProvider } from "./opencontext";
import PageTransition from './components/PageTransition'
import StairEffect from './components/StairEffect'


const koho = KoHo({ 
  subsets: ["latin"], 
  weight: ["700" ],
  variable: '--font-koho',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={koho.variable}>
        <OpenProvider>
          <div className="w-full h-full">
            <div className="h-24">
              <Navbar/>
            </div>
            <StairEffect />
            <PageTransition>
              <div className="h-[calc(100vh-6rem)]">
                {children}
              </div>
            </PageTransition>
          </div>
        </OpenProvider>
      </body>
    </html>
  );
}


